apiVersion: compute.kraftcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    metro: dal0
    image: unikraft.io/nderjung.unikraft.io/http-go1.21/latest
    memory: "64Mi"
    args:
    - "/server"
    internalPort: 8080
    port: 443
    desiredState: stopped
  providerConfigRef:
    name: example
