apiVersion: compute.kraftcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example2
spec:
  forProvider:
    image: unikraft.io/jayc.unikraft.io/mynginx:latest
    memory: "64Mi"
    args:
    - "-c"
    - "/nginx/conf/nginx.conf"
    internalPort: 80
    port: 443
    desiredState: started
  providerConfigRef:
    name: example
